### ISSUE TITLE
Missing file baselineSample.fits

### ISSUE THREAD

**Issue by wilbertras** [fdannert/LIFEsim#21]
The line `bus.data.catalog_from_ppop(input_path='path_to_LIFEsim/LIFEsim/docs/_static/baselineSample.fits')` raises an error as no such file is found in the directory. This file is used for loading the catalogue in the 'Simulating the Search Phase' example.

**Comment by fdannert** [comment]
Dear @wilbertras,
thank you very much for spotting that! I have updated the lifesim_demo.py file and the documentation to automatically download a P-Pop synthetic planet population from the P-Pop GitHub website.

Let me know if that does not solve the issue for you, otherwise I will close this Issue.

Best,
Felix
